name: Prod Pipeline

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_FATHI }}" --password-stdin

      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_FATHI }}/book_shop:${{ vars.IMAGE_VERSION }}

      - name: Deploy
        run: |
          docker stop book_shop_prod || true
          docker rm book_shop_prod || true
          docker run -d --name book_shop_prod -p 8080:8000 ${{ secrets.DOCKERHUB_FATHI }}/book_shop:${{ vars.IMAGE_VERSION }}